/**
 * Chart export utilities — PNG and PDF export from SVG charts
 */
import jsPDF from 'jspdf';

async function svgToCanvas(svg: SVGSVGElement, scale: number = 3): Promise<HTMLCanvasElement> {
  const clone = svg.cloneNode(true) as SVGSVGElement;
  clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');

  // Get dimensions from viewBox
  const viewBox = svg.getAttribute('viewBox') || '0 0 1400 1400';
  const [, , vbW, vbH] = viewBox.split(/\s+/).map(Number);
  clone.setAttribute('width', String(vbW));
  clone.setAttribute('height', String(vbH));

  // Inline computed font styles for text elements
  const origTexts = svg.querySelectorAll('text');
  const cloneTexts = clone.querySelectorAll('text');
  origTexts.forEach((origText, i) => {
    if (cloneTexts[i]) {
      const computed = window.getComputedStyle(origText);
      (cloneTexts[i] as SVGTextElement).style.fontFamily = computed.fontFamily;
      (cloneTexts[i] as SVGTextElement).style.fontSize = computed.fontSize;
    }
  });

  const svgData = new XMLSerializer().serializeToString(clone);
  const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);

  const width = vbW * scale;
  const height = vbH * scale;

  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d')!;
      ctx.drawImage(img, 0, 0, width, height);
      URL.revokeObjectURL(url);
      resolve(canvas);
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Failed to render chart'));
    };
    img.src = url;
  });
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function exportChartAsPNG(
  container: HTMLElement,
  filename: string = 'chart.png'
): Promise<void> {
  const svg = container.querySelector('svg');
  if (!svg) throw new Error('No chart found');

  const canvas = await svgToCanvas(svg as SVGSVGElement);
  const blob = await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob(
      (b) => (b ? resolve(b) : reject(new Error('Failed to create image'))),
      'image/png'
    );
  });
  triggerDownload(blob, filename);
}

export async function exportChartAsPDF(
  container: HTMLElement,
  filename: string = 'chart.pdf',
  title?: string
): Promise<void> {
  const svg = container.querySelector('svg');
  if (!svg) throw new Error('No chart found');

  const canvas = await svgToCanvas(svg as SVGSVGElement);
  const imgData = canvas.toDataURL('image/png');

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  let yOffset = 10;
  if (title) {
    pdf.setFontSize(16);
    pdf.text(title, pageWidth / 2, 15, { align: 'center' });
    yOffset = 22;
  }

  const availableSize = Math.min(pageWidth - 20, pageHeight - yOffset - 15);
  const x = (pageWidth - availableSize) / 2;
  pdf.addImage(imgData, 'PNG', x, yOffset, availableSize, availableSize);

  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text('Generated by Astrologer', pageWidth / 2, pageHeight - 5, { align: 'center' });

  pdf.save(filename);
}
