/**
 * Chart export utilities — PNG, PDF export, and email sharing from SVG charts
 */
import jsPDF from 'jspdf';
import { supabase } from '@/lib/supabase';

async function svgToCanvas(svg: SVGSVGElement, scale: number = 3): Promise<HTMLCanvasElement> {
  const clone = svg.cloneNode(true) as SVGSVGElement;
  clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');

  // Get dimensions from viewBox
  const viewBox = svg.getAttribute('viewBox') || '0 0 1400 1400';
  const [, , vbW, vbH] = viewBox.split(/\s+/).map(Number);
  clone.setAttribute('width', String(vbW));
  clone.setAttribute('height', String(vbH));

  // Inline computed font styles for text elements
  const origTexts = svg.querySelectorAll('text');
  const cloneTexts = clone.querySelectorAll('text');
  origTexts.forEach((origText, i) => {
    if (cloneTexts[i]) {
      const computed = window.getComputedStyle(origText);
      (cloneTexts[i] as SVGTextElement).style.fontFamily = computed.fontFamily;
      (cloneTexts[i] as SVGTextElement).style.fontSize = computed.fontSize;
    }
  });

  const svgData = new XMLSerializer().serializeToString(clone);
  const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);

  const width = vbW * scale;
  const height = vbH * scale;

  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext('2d')!;
      ctx.drawImage(img, 0, 0, width, height);
      URL.revokeObjectURL(url);
      resolve(canvas);
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error('Failed to render chart'));
    };
    img.src = url;
  });
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export async function exportChartAsPNG(
  container: HTMLElement,
  filename: string = 'chart.png'
): Promise<void> {
  const svg = container.querySelector('svg');
  if (!svg) throw new Error('No chart found');

  const canvas = await svgToCanvas(svg as SVGSVGElement);
  const blob = await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob(
      (b) => (b ? resolve(b) : reject(new Error('Failed to create image'))),
      'image/png'
    );
  });
  triggerDownload(blob, filename);
}

export async function exportChartAsPDF(
  container: HTMLElement,
  filename: string = 'chart.pdf',
  title?: string
): Promise<void> {
  const svg = container.querySelector('svg');
  if (!svg) throw new Error('No chart found');

  const canvas = await svgToCanvas(svg as SVGSVGElement);
  const imgData = canvas.toDataURL('image/png');

  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  let yOffset = 10;
  if (title) {
    pdf.setFontSize(16);
    pdf.text(title, pageWidth / 2, 15, { align: 'center' });
    yOffset = 22;
  }

  const availableSize = Math.min(pageWidth - 20, pageHeight - yOffset - 15);
  const x = (pageWidth - availableSize) / 2;
  pdf.addImage(imgData, 'PNG', x, yOffset, availableSize, availableSize);

  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text('Generated by Astrologer', pageWidth / 2, pageHeight - 5, { align: 'center' });

  pdf.save(filename);
}

/**
 * Capture chart as base64 PNG (for email attachment)
 */
export async function captureChartAsBase64(
  container: HTMLElement,
  scale: number = 2
): Promise<string> {
  const svg = container.querySelector('svg');
  if (!svg) throw new Error('No chart found');

  const canvas = await svgToCanvas(svg as SVGSVGElement, scale);
  // Return base64 without the data:image/png;base64, prefix
  const dataUrl = canvas.toDataURL('image/png');
  return dataUrl.replace(/^data:image\/png;base64,/, '');
}

/**
 * Send chart via email using Resend (via Supabase edge function)
 */
export async function emailChart(params: {
  container: HTMLElement;
  to: string;
  title: string;
  message?: string;
  chartDetails?: string;
}): Promise<void> {
  const { container, to, title, message, chartDetails } = params;

  // Capture chart as base64
  const chartBase64 = await captureChartAsBase64(container, 2);

  // Build HTML email
  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head>
<body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0a0a;">
    <tr><td align="center" style="padding:40px 20px;">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#171717;border-radius:16px;overflow:hidden;">
        <!-- Header -->
        <tr><td style="padding:32px 32px 16px;text-align:center;">
          <h1 style="margin:0;font-size:22px;font-weight:700;color:#ffffff;letter-spacing:-0.02em;">${escapeHtml(title)}</h1>
          ${chartDetails ? `<p style="margin:8px 0 0;font-size:13px;color:#a1a1aa;">${escapeHtml(chartDetails)}</p>` : ''}
        </td></tr>
        ${message ? `
        <!-- Message -->
        <tr><td style="padding:0 32px 16px;">
          <div style="background:#262626;border-radius:12px;padding:16px;font-size:14px;color:#d4d4d8;line-height:1.5;">
            ${escapeHtml(message)}
          </div>
        </td></tr>
        ` : ''}
        <!-- Chart Image -->
        <tr><td style="padding:0 24px 24px;">
          <img src="cid:chart-image" alt="Astrology Chart" style="width:100%;border-radius:12px;display:block;" />
        </td></tr>
        <!-- CTA -->
        <tr><td style="padding:0 32px 32px;text-align:center;">
          <a href="https://astrologer.app" style="display:inline-block;padding:12px 32px;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;text-decoration:none;border-radius:10px;font-size:14px;font-weight:600;">Create Your Chart</a>
        </td></tr>
        <!-- Footer -->
        <tr><td style="padding:16px 32px 24px;border-top:1px solid #262626;text-align:center;">
          <p style="margin:0;font-size:11px;color:#525252;">Sent from <a href="https://astrologer.app" style="color:#6366f1;text-decoration:none;">Astrologer</a></p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`.trim();

  const { data, error } = await supabase.functions.invoke('send-email', {
    body: {
      to,
      subject: `${title} — Astrologer Chart`,
      html,
      from: 'Astrologer <charts@astrologyapp.org>',
      skipDeletedCheck: true,
      attachments: [
        {
          filename: 'chart.png',
          content: chartBase64,
          content_type: 'image/png',
        },
      ],
    },
  });

  if (error) throw new Error(error.message || 'Failed to send email');
  if (data?.error) throw new Error(data.error);
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
