import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors mb-8">
          <ArrowLeft className="w-4 h-4" />
          Back
        </Link>

        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: February 25, 2026</p>

        <div className="prose prose-sm dark:prose-invert max-w-none space-y-8 text-foreground/80">
          <section>
            <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>By accessing or using Astrologer ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">2. Description of Service</h2>
            <p>Astrologer is a web-based astrology tool that provides natal chart calculations, synastry analysis, transit timelines, profections, graphic ephemeris, astrocartography, 3D galactic visualizations, and AI-powered chart interpretations. Calculations are powered by the Swiss Ephemeris.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">3. Accounts</h2>
            <p>Some features require an account. You are responsible for maintaining the confidentiality of your credentials. You must provide accurate information when creating an account.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">4. Subscriptions & Payments</h2>
            <p>Astrologer offers free and paid tiers. Paid subscriptions are billed through Stripe. You may cancel at any time; access continues until the end of the billing period. Refunds are handled on a case-by-case basis.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">5. Free Tier Limits</h2>
            <p>Free accounts receive limited AI readings (3/month), limited saved charts (3), and limited relocated chart calculations (3/month). These limits reset on the 1st of each month.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">6. AI Readings Disclaimer</h2>
            <p>AI-powered chart interpretations are generated by artificial intelligence and are provided for entertainment and self-reflection purposes only. They do not constitute professional advice of any kind — including psychological, medical, financial, or legal advice. Use your own judgement.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">7. Astrological Services Disclaimer</h2>
            <p>All astrological calculations and interpretations are provided for informational and entertainment purposes. Astrologer makes no claims about the predictive accuracy of astrology. Do not make life decisions based solely on astrological information.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">8. Intellectual Property</h2>
            <p>All content, design, code, and visual assets of Astrologer are owned by us. You may not copy, modify, or distribute any part of the Service without written permission. Charts you generate from your own data are yours to keep and share.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">9. Acceptable Use</h2>
            <p>You agree not to: (a) abuse the Service or attempt to circumvent usage limits; (b) use the Service for any unlawful purpose; (c) attempt to reverse-engineer the Service; (d) scrape or automate access to the Service without permission.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">10. Data & Privacy</h2>
            <p>Your use of the Service is also governed by our <Link to="/privacy" className="text-primary underline">Privacy Policy</Link>. Birth data you enter is used solely to calculate charts and is stored locally or in your account if you choose to save it.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">11. Limitation of Liability</h2>
            <p>The Service is provided "as is" without warranty of any kind. We are not liable for any damages arising from your use of the Service, including but not limited to decisions made based on astrological or AI-generated content.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">12. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time by contacting support.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">13. Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">14. Contact</h2>
            <p>Questions about these terms? Reach us at <a href="mailto:zeineddine.jad@gmail.com" className="text-primary underline">zeineddine.jad@gmail.com</a> or visit our <Link to="/support" className="text-primary underline">Support</Link> page.</p>
          </section>
        </div>
      </div>
    </div>
  );
}
